import { createHash } from 'node:crypto';
import { createSign } from 'node:crypto';
import { z } from 'zod';

export const SEARCH_ACTIONS=['improve_title_meta','strengthen_internal_links','refresh_verified_inventory','create_landing_page_candidate','improve_cta','consolidate_duplicate_intent','review_stale_page','request_inventory_verification'];
export function validateSeoAction(value){return ['approved','dismissed','snoozed','reviewed'].includes(value?.status)&&SEARCH_ACTIONS.includes(value?.action_type)&&typeof value?.recommendation_id==='string'&&value.recommendation_id.length>0;}
const rowSchema=z.object({query:z.string().trim().min(1).max(1000),page:z.string().url().max(2048),clicks:z.number().int().nonnegative(),impressions:z.number().int().nonnegative(),ctr:z.number().min(0).max(1),position:z.number().nonnegative(),date:z.string().date(),device:z.string().trim().max(40).optional().nullable(),country:z.string().trim().max(3).optional().nullable()}).refine(x=>x.clicks<=x.impressions,{message:'Clicks cannot exceed impressions'});
export const importSchema=z.object({report_start:z.string().date(),report_end:z.string().date(),source:z.literal('google_search_console'),environment:z.enum(['production','preview','development','test']),is_test:z.boolean(),rows:z.array(rowSchema).min(1).max(25000)}).refine(x=>x.report_start<=x.report_end,{message:'Invalid reporting period'}).refine(x=>x.is_test=== (x.environment==='test'),{message:'TEST isolation mismatch'});
export const fingerprint=(r,b)=>createHash('sha256').update([b.environment,b.is_test,r.date,r.query,r.page,r.device||'',r.country||''].join('\0')).digest('hex');
export function connectionState(env=process.env){const missing=['GOOGLE_SEARCH_CONSOLE_SITE_URL','GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL','GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY'].filter(k=>!String(env[k]||'').trim());return {connected:missing.length===0,status:missing.length?'NOT CONNECTED':'CONNECTED',missing,required:['GOOGLE_SEARCH_CONSOLE_SITE_URL','GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL','GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY'],message:missing.length?'Configure the listed environment variables in the production deployment; never paste secrets into the browser.':'Credentials are configured. Imported persisted data is reported separately.'};}

const b64=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
export async function fetchSearchConsoleReport({startDate,endDate,env=process.env,fetchImpl=fetch}){
 const state=connectionState(env);if(!state.connected)throw Object.assign(new Error('Search Console is not configured.'),{code:'not_configured'});
 const now=Math.floor(Date.now()/1000),header=b64({alg:'RS256',typ:'JWT'}),claims=b64({iss:env.GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL,scope:'https://www.googleapis.com/auth/webmasters.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});
 const signer=createSign('RSA-SHA256');signer.update(`${header}.${claims}`);signer.end();
 const assertion=`${header}.${claims}.${signer.sign(String(env.GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY).replace(/\\n/g,'\n'),'base64url')}`;
 const tokenResponse=await fetchImpl('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion})});
 if(!tokenResponse.ok)throw Object.assign(new Error('Google service-account authentication failed.'),{code:'google_auth_failed'});const {access_token:token}=await tokenResponse.json();
 const reportResponse=await fetchImpl(`https://www.googleapis.com/webmasters/v3/sites/${encodeURIComponent(env.GOOGLE_SEARCH_CONSOLE_SITE_URL)}/searchAnalytics/query`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({startDate,endDate,dimensions:['date','query','page','device','country'],rowLimit:25000,dataState:'final'})});
 if(!reportResponse.ok)throw Object.assign(new Error('Google Search Console report request failed.'),{code:'google_report_failed'});const report=await reportResponse.json();
 return (report.rows||[]).map(row=>({date:row.keys[0],query:row.keys[1],page:row.keys[2],device:row.keys[3]||null,country:row.keys[4]||null,clicks:Math.round(row.clicks),impressions:Math.round(row.impressions),ctr:row.ctr,position:row.position}));
}

const intent=(q,context={})=>{const s=q.toLowerCase();if(context.projects?.some(x=>s.includes(String(x).toLowerCase())))return ['exact_project',100];if(context.areas?.some(x=>s.includes(String(x).toLowerCase()))&&/(apartment|villa|property|townhouse)/.test(s))return ['area_property_type',90];if(context.areas?.some(x=>s.includes(String(x).toLowerCase()))&&/\b\d+\s*(bed|bedroom)/.test(s))return ['area_bedroom',85];if(/(under|aed|budget|million)/.test(s))return ['property_budget',80];if(context.developers?.some(x=>s.includes(String(x).toLowerCase())))return ['developer',70];if(/ready/.test(s))return ['ready_property',60];if(/off.?plan/.test(s))return ['off_plan',50];return ['investment_education',30];};
export function buildOpportunities(rows,{pages=[],inventory=[],leads=[],now=new Date()}={}){
 const pageKey=value=>{try{return new URL(value,'https://finding-stories.com').pathname.replace(/\/$/,'')||'/';}catch{return String(value||'').replace(/\/$/,'');}};
 const prod=rows.filter(x=>!x.is_test), pageMap=new Map(pages.map(x=>[pageKey(x.url||x.page||x.path),x])), contexts={projects:[...new Set(inventory.map(x=>x.project).filter(Boolean))],areas:[...new Set(inventory.map(x=>x.area).filter(Boolean))],developers:[...new Set(inventory.map(x=>x.developer).filter(Boolean))]};
 const grouped=new Map();for(const r of prod){const k=`${r.query}\0${r.page}`;const a=grouped.get(k)||{query:r.query,page:r.page,clicks:0,impressions:0,weighted_position:0,last_date:r.date};a.clicks+=r.clicks;a.impressions+=r.impressions;a.weighted_position+=r.position*r.impressions;a.last_date=a.last_date>r.date?a.last_date:r.date;grouped.set(k,a);}
 const out=[];const add=(type,a,action,reason,bonus=0)=>{const [commercial_intent,intent_score]=intent(a.query,contexts),coverage=inventory.filter(x=>!x.is_test&&x.status==='active'&&x.data_quality==='verified'&&(a.page.includes(String(x.area||'').toLowerCase().replace(/\W+/g,'-'))||a.query.toLowerCase().includes(String(x.project||'').toLowerCase()))).length;const attributed=leads.filter(x=>!x.is_test&&x.source==='organic'&&x.search_query===a.query&&x.landing_page===a.page);out.push({id:createHash('sha256').update(`${type}\0${a.query}\0${a.page}`).digest('hex').slice(0,24),type,query:a.query,target_page:a.page,clicks:a.clicks,impressions:a.impressions,ctr:a.impressions?a.clicks/a.impressions:0,average_position:a.impressions?a.weighted_position/a.impressions:0,verified_inventory_coverage:coverage,commercial_intent,metrics:attribution(attributed),recommendation:action,reason,priority:intent_score+bonus,data_freshness:a.last_date});};
 for(const a of grouped.values()){const ctr=a.impressions?a.clicks/a.impressions:0,pos=a.impressions?a.weighted_position/a.impressions:0,linked=leads.filter(x=>!x.is_test&&x.source==='organic'&&pageKey(x.landing_page)===pageKey(a.page));const page=pageMap.get(pageKey(a.page));if(a.impressions>=100&&ctr<.02)add('high_impressions_low_ctr',a,'improve_title_meta','Meaningful impressions with CTR below 2%.',15);if(a.impressions>=20&&pos>=4&&pos<=15)add('near_page_one',a,'strengthen_internal_links','Average position is between 4 and 15.',12);if(a.clicks>0&&!linked.length)add('traffic_zero_leads',a,'improve_cta','Persisted organic clicks exist with no attributable enquiry.',10);if(linked.length&&a.clicks<10)add('leads_low_traffic',a,'strengthen_internal_links','Attributable leads exist despite fewer than 10 clicks.',8);if(!page)add('missing_page',a,'create_landing_page_candidate','No eligible landing page matches this demand.',5);const cov=inventory.filter(x=>!x.is_test&&x.status==='active'&&x.data_quality==='verified').length;if(!cov)add('inventory_gap',a,'request_inventory_verification','No verified production inventory supports safe publication.',20);if(page?.updated_at&&now-new Date(page.updated_at)>90*864e5)add('stale_page',a,'review_stale_page','Page has not been updated for more than 90 days.',10);if(page&&pages.some(x=>x!==page&&(x.area&&x.area===page.area||x.project&&x.project===page.project)))add('internal_link_opportunity',a,'strengthen_internal_links','A related eligible page can provide a relevant internal link.',4);}
 const dated=[...new Set(prod.map(x=>x.date))].sort();if(dated.length>1){const split=dated[Math.floor(dated.length/2)],sum=(rows,key)=>rows.reduce((n,x)=>n+x[key],0);for(const a of grouped.values()){const matching=prod.filter(x=>x.query===a.query&&x.page===a.page),before=matching.filter(x=>x.date<split),after=matching.filter(x=>x.date>=split);if(!before.length||!after.length)continue;const prior=sum(before,'impressions'),recent=sum(after,'impressions');if(prior>=10&&recent>=prior*1.25)add('growing_query',a,'strengthen_internal_links','Recent genuine impressions grew by at least 25% versus the preceding period.',8);if(prior>=20&&recent<=prior*.75)add('declining_page',a,'review_stale_page','Recent genuine impressions declined by at least 25% versus the preceding period.',10);}}
 return out.sort((a,b)=>b.priority-a.priority||b.impressions-a.impressions);
}
export function attribution(leads=[]){return {enquiries:leads.length,qualified_leads:leads.filter(x=>x.qualified_at||x.status==='qualified').length,meetings:leads.filter(x=>x.meeting_at).length,site_visits:leads.filter(x=>x.site_visit_at).length,bookings:leads.filter(x=>x.status==='booked').length};}
