import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';
import { deletionResult,hasStrictDeleteRole,parseLeadDeletion } from '../api/_lib/crm/lead-deletion.js';
import { canDeleteLeads,selectedListedIds,toggleAllListed } from '../public/crm-lead-selection.js';
const IDS=['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003'];

test('request parsing supports explicit TEST fixtures and result details',()=>{assert.deepEqual(parseLeadDeletion({ids:[IDS[0]],confirm:true}),[IDS[0]]);assert.equal(hasStrictDeleteRole({role:'SUPER_ADMIN'}),true);assert.deepEqual(deletionResult([{lead_id:IDS[0],deleted:false,reason:'shared relation x'}],[IDS[0]]),{deletedCount:0,deletedIds:[],notDeleted:[{id:IDS[0],reason:'shared relation x'}]});});
test('selection is bounded to displayed leads and every other role is denied',()=>{const selected=toggleAllListed(new Set([IDS[2]]),IDS.slice(0,2),true);assert.deepEqual([...selectedListedIds(selected,IDS.slice(0,2))],IDS.slice(0,2));for(const role of ['ADMIN','TEAM_LEADER','AGENT',null]){assert.equal(hasStrictDeleteRole({role}),false);assert.equal(canDeleteLeads(role),false);}});

async function fixtureDb(){
 const db=new PGlite();
 await db.exec(`CREATE TABLE crm_users(id uuid primary key, role text, active boolean); CREATE TABLE leads(id uuid primary key,is_test boolean,name text,phone text,email text,agent_notes text,whatsapp_follow_up_draft text,call_opener text);
 CREATE TABLE crm_audit_logs(id bigserial primary key,actor_id uuid references crm_users(id),action text,entity_type text,entity_id text,before_value jsonb,after_value jsonb,ip_address text,created_at timestamptz);
 CREATE TABLE launch_projects(id uuid primary key); CREATE TABLE launch_campaigns(id uuid primary key); CREATE TABLE property_inventory(id uuid primary key); CREATE TABLE search_console_snapshots(id bigserial primary key);
 CREATE TABLE crm_opportunities(id uuid primary key,lead_id uuid references leads(id)); CREATE TABLE launch_eois(id uuid primary key,lead_id uuid references leads(id),opportunity_id uuid references crm_opportunities(id));
 CREATE TABLE launch_funnel_history(id bigserial primary key,lead_id uuid references leads(id),eoi_id uuid references launch_eois(id)); CREATE TABLE crm_tasks(id uuid primary key,lead_id uuid references leads(id),opportunity_id uuid references crm_opportunities(id)); CREATE TABLE crm_activities(id uuid primary key,lead_id uuid references leads(id),opportunity_id uuid references crm_opportunities(id));
 CREATE TABLE launch_lead_attribution(id uuid primary key,lead_id uuid references leads(id),duplicate_of_lead_id uuid references leads(id)); CREATE TABLE follow_up_executions(id uuid primary key,lead_id uuid references leads(id)); CREATE TABLE property_recommendations(id uuid primary key,lead_id uuid references leads(id));`);
 await db.exec(await readFile('database/migrations/016_super_admin_lead_deletion_fix.sql','utf8'));
 await db.exec(`INSERT INTO crm_users VALUES('${IDS[2]}','SUPER_ADMIN',true),('10000000-0000-4000-8000-000000000003','ADMIN',true); INSERT INTO leads VALUES('${IDS[0]}',false,'normal','1',null,null,null,null),('${IDS[1]}',true,'test','2',null,null,null,null),('${IDS[2]}',false,'single','3',null,null,null,null); INSERT INTO launch_projects VALUES(gen_random_uuid()); INSERT INTO launch_campaigns VALUES(gen_random_uuid()); INSERT INTO property_inventory VALUES(gen_random_uuid()); INSERT INTO search_console_snapshots DEFAULT VALUES;`);
 return db;
}

test('PostgreSQL deletion transaction enforces authorization, cleanup, TEST deletion, auditing and safe failures',async t=>{
 const db=await fixtureDb();
 await t.test('unauthorized user receives insufficient_privilege for the API to return 403',async()=>{await assert.rejects(db.query(`SELECT * FROM delete_crm_leads('["${IDS[0]}"]','10000000-0000-4000-8000-000000000003',NULL)`),error=>error.code==='42501');});
 await t.test('SUPER_ADMIN single delete succeeds',async()=>{const single=await db.query(`SELECT * FROM delete_crm_leads('["${IDS[2]}"]','${IDS[2]}',NULL)`);assert.equal(single.rows[0].deleted,true);});
 await t.test('SUPER_ADMIN bulk delete cleans owned dependencies including a TEST lead and preserves unrelated records',async()=>{await db.exec(`INSERT INTO crm_opportunities VALUES('20000000-0000-4000-8000-000000000001','${IDS[0]}'); INSERT INTO crm_tasks VALUES(gen_random_uuid(),'${IDS[0]}','20000000-0000-4000-8000-000000000001'); INSERT INTO crm_activities VALUES(gen_random_uuid(),'${IDS[0]}','20000000-0000-4000-8000-000000000001'); INSERT INTO follow_up_executions VALUES(gen_random_uuid(),'${IDS[1]}'); INSERT INTO property_recommendations VALUES(gen_random_uuid(),'${IDS[1]}');`);const result=await db.query(`SELECT * FROM delete_crm_leads('["${IDS[0]}","${IDS[1]}"]','${IDS[2]}',NULL)`);assert.deepEqual(result.rows.map(x=>x.deleted),[true,true],JSON.stringify(result.rows));assert.equal((await db.query('SELECT count(*)::int n FROM crm_tasks')).rows[0].n,0);assert.equal((await db.query('SELECT count(*)::int n FROM crm_audit_logs')).rows[0].n,3);for(const table of ['launch_projects','launch_campaigns','property_inventory','search_console_snapshots','crm_users'])assert.ok((await db.query(`SELECT count(*)::int n FROM ${table}`)).rows[0].n>0);});
 await t.test('an unknown shared FK returns its exact relation and rolls back audit',async()=>{await db.exec(`INSERT INTO leads VALUES('${IDS[0]}',false,'blocked','4',null,null,null,null); CREATE TABLE shared_links(id uuid primary key,lead_id uuid references leads(id)); INSERT INTO shared_links VALUES(gen_random_uuid(),'${IDS[0]}');`);const audits=(await db.query('SELECT count(*)::int n FROM crm_audit_logs')).rows[0].n;const result=await db.query(`SELECT * FROM delete_crm_leads('["${IDS[0]}"]','${IDS[2]}',NULL)`);assert.equal(result.rows[0].deleted,false);assert.match(result.rows[0].reason,/shared_links/);assert.equal((await db.query('SELECT count(*)::int n FROM crm_audit_logs')).rows[0].n,audits);});
 await db.close();
});

test('migration never deletes shared production domains and audit does not reference leads',async()=>{const sql=await readFile('database/migrations/016_super_admin_lead_deletion_fix.sql','utf8');for(const table of ['property_inventory','launch_campaigns','launch_projects','search_console_snapshots','crm_users'])assert.doesNotMatch(sql,new RegExp(`DELETE FROM ${table}`));assert.match(sql,/DELETE FROM leads l WHERE l.id=requested/);assert.doesNotMatch(sql,/is_test=FALSE/);const foundation=await readFile('database/migrations/010_crm_foundation.sql','utf8');assert.match(foundation,/entity_id TEXT/);assert.doesNotMatch(foundation,/entity_id[^,]*REFERENCES leads/);});
