import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {assertNoAliasConflicts,deterministicMappingKey,mapDldArea,mapDldProject} from '../data-sources/dld/mapping.js';
import {generateDldMappingReview,mappingEligibility,projectReviewSuggestions,recordsForPage} from '../data-sources/dld/mapping-review.js';

test('exact and verified area mappings use only governed normalization',()=>{assert.equal(mapDldArea(' business--bay ').status,'EXACT');assert.equal(mapDldArea('AL BARSHAA SOUTH THIRD').status,'VERIFIED_ALIAS');assert.equal(deterministicMappingKey('Dubai—Marina'),'dubai marina')});
test('uncertain names are preserved as unmapped and never fuzzy-published',()=>{assert.deepEqual(mapDldArea('Business Bays'),{status:'UNMAPPED',canonicalName:null,canonicalSlug:null,method:null,verificationSource:null});assert.equal(mapDldProject('Azizi Florance').status,'UNMAPPED')});
test('project exact match verifies project and developer from published registry',()=>{const mapped=mapDldProject(' AZIZI-FLORENCE ');assert.equal(mapped.status,'EXACT');assert.equal(mapped.developer,'Azizi Developments')});
test('duplicate source aliases mapping to conflicting entities fail closed',()=>assert.throws(()=>assertNoAliasConflicts([{source:'Same',slug:'one'},{source:' same ',slug:'two'}],{sourceField:'source',canonicalField:'slug'}),/Conflicting/));
test('page attribution gates areas, projects, and developers independently',()=>{const records=[{areaMappingStatus:'UNMAPPED',projectMappingStatus:'UNMAPPED',canonicalAreaSlug:'business-bay',canonicalProjectSlug:'azizi-florence',developer:'Azizi Developments'},{areaMappingStatus:'EXACT',projectMappingStatus:'EXACT',canonicalAreaSlug:'business-bay',canonicalProjectSlug:'azizi-florence',developer:'Azizi Developments'}];assert.deepEqual(mappingEligibility(records[0]),{area:false,project:false,developer:false});assert.equal(recordsForPage(records,{areaSlug:'business-bay'}).length,1);assert.equal(recordsForPage(records,{projectSlug:'azizi-florence'}).length,1);assert.equal(recordsForPage(records,{developer:'Azizi Developments'}).length,1)});
test('mapping artifacts retain originals and keep suggestions review-only',async()=>{const dir=await mkdtemp(join(tmpdir(),'dld-map-'));const report=await generateDldMappingReview([{sourceAreaName:'BUSINESS BAY',project:'Azizi Florence',amountAed:5},{sourceAreaName:'Business Bays',project:'Azizi Florance',amountAed:10}],{outputDirectory:dir});assert.deepEqual({areas_total:report.areas_total,areas_exact:report.areas_exact,areas_unmapped:report.areas_unmapped,projects_total:report.projects_total,projects_exact:report.projects_exact,projects_unmapped:report.projects_unmapped},{areas_total:2,areas_exact:1,areas_unmapped:1,projects_total:2,projects_exact:1,projects_unmapped:1});const unmapped=JSON.parse(await readFile(join(dir,'dld-areas-unmapped.json'),'utf8'));assert.equal(unmapped[0].source_area,'Business Bays');const suggestions=JSON.parse(await readFile(join(dir,'dld-area-suggestions.json'),'utf8'));assert.ok(suggestions.every(item=>item.status==='REVIEW_ONLY'&&!item.publishable))});
test('developer overlap alone never suggests a distinct Azizi project as Florence',async()=>{const sources=['AZIZI AMBER','AZIZI JEWEL','AZIZI MILAN 51','AZIZI NEILA','AZIZI RIVIERA 61','AZIZI RIVIERA 63','AZIZI RIVIERA 65','AZIZI RIVIERA 67','AZIZI RIVIERA 69'];const target=[{name:'Azizi Florence',slug:'azizi-florence',developer:'Azizi Developments'}];assert.deepEqual(projectReviewSuggestions(sources,target),[]);for(const source of sources)assert.equal(mapDldProject(source).status,'UNMAPPED');const dir=await mkdtemp(join(tmpdir(),'dld-project-map-'));await generateDldMappingReview(sources.map(project=>({project})),{outputDirectory:dir});assert.deepEqual(JSON.parse(await readFile(join(dir,'dld-project-suggestions.json'),'utf8')),[])});
test('project suggestions require project-specific overlap and stay review-only',()=>{const suggestions=projectReviewSuggestions(['Florence Phase 2','Azizi Tower'],[{name:'Azizi Florence',slug:'azizi-florence',developer:'Azizi Developments'}]);assert.deepEqual(suggestions.map(item=>item.source),['Florence Phase 2']);assert.ok(suggestions.every(item=>item.status==='REVIEW_ONLY'&&item.publishable===false));assert.deepEqual(projectReviewSuggestions(['DAMAC TOWER'],[{name:'Damac Tower',slug:'damac-tower',developer:'Damac Properties'}]),[])});
