import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {acquireDldToken,clearDldTokenCache} from '../data-sources/dld/auth.js';import {fetchDldSnapshot} from '../data-sources/dld/adapter.js';import {normalizeDldRecords} from '../data-sources/dld/normalize.js';import {aggregateDldTransactions} from '../data-sources/dld/aggregate.js';
const env={DUBAI_PULSE_DLD_API_URL:'https://official.example/data',DUBAI_PULSE_TOKEN_URL:'https://official.example/token',DUBAI_PULSE_API_KEY:'key',DUBAI_PULSE_API_SECRET:'secret'};
const response=(body,status=200,headers={get:()=>null})=>({ok:status>=200&&status<300,status,headers,json:async()=>body});
const raw=(id,amount=1000,size=10,date='2026-09-01')=>({transaction_id:id,instance_date:date,procedure_name_en:'Sale',actual_worth:amount,property_size_sqm:size,area_name_en:'Marina',property_type_en:'Apartment'});
test('OAuth uses Basic client credentials, caches until expiry, and does not leak secrets',async()=>{clearDldTokenCache();let calls=0,options;const fetchImpl=async(_url,o)=>{calls++;options=o;return response({access_token:'private-token',token_type:'Bearer',expires_in:300})};assert.equal(await acquireDldToken({tokenUrl:env.DUBAI_PULSE_TOKEN_URL,apiKey:'key',apiSecret:'secret',fetchImpl}),'Bearer private-token');await acquireDldToken({tokenUrl:env.DUBAI_PULSE_TOKEN_URL,apiKey:'key',apiSecret:'secret',fetchImpl});assert.equal(calls,1);assert.match(options.headers.authorization,/^Basic /);assert.doesNotMatch(JSON.stringify(options.body),/secret/)});
test('connector paginates, validates, normalizes and deduplicates official records',async()=>{clearDldTokenCache();const dir=await mkdtemp(join(tmpdir(),'dld-'));const fetchImpl=async(url)=>String(url).includes('/token')?response({access_token:'t',expires_in:300}):response(new URL(url).searchParams.get('page')==='1'?{records:[raw('one'),raw('one')],nextPage:2}:{records:[raw('two')],totalPages:2});const result=await fetchDldSnapshot({env,fetchImpl,cachePath:join(dir,'cache.json'),now:()=>new Date('2026-09-13T10:00:00Z')});assert.equal(result.status,'verified');assert.equal(result.records.length,2);assert.equal(result.health.records_received,3);assert.equal(result.health.records_rejected,1);assert.equal(result.records[0].provenance.sourceId,'one')});
test('normalizer retains supported fields and leaves missing values null',()=>{const {records}=normalizeDldRecords([{...raw('x'),reg_type_en:'Off Plan',is_free_hold:'Yes',property_sub_type_en:'Flat',procedure_area:'9',rooms_en:'2 B/R',has_parking:'1',master_project_en:'Master',project_name_en:'Project',no_of_parties_role_1:'2',no_of_parties_role_2:1}]);assert.deepEqual({...records[0],transactionSubtype:undefined,nearestMetro:undefined,nearestMall:undefined,nearestLandmark:undefined,transactionSizeSqft:undefined,propertySizeSqft:undefined,aedPerSqft:undefined,sourceAreaName:undefined,canonicalAreaName:undefined,canonicalAreaSlug:undefined,areaMappingStatus:undefined,areaMappingMethod:undefined,projectMappingStatus:undefined,canonicalProject:undefined,canonicalProjectSlug:undefined,developer:undefined},{sourceId:'x',transactionDate:'2026-09-01',transactionType:'Sale',transactionSubtype:undefined,registrationType:'Off Plan',freehold:'Yes',usage:null,area:'Marina',propertyType:'Apartment',propertySubtype:'Flat',amountAed:1000,transactionSizeSqm:9,propertySizeSqm:10,rooms:'2 B/R',parking:'1',masterProject:'Master',project:'Project',buyerCount:2,sellerCount:1,nearestMetro:undefined,nearestMall:undefined,nearestLandmark:undefined,transactionSizeSqft:undefined,propertySizeSqft:undefined,aedPerSqft:undefined,sourceAreaName:undefined,canonicalAreaName:undefined,canonicalAreaSlug:undefined,areaMappingStatus:undefined,areaMappingMethod:undefined,projectMappingStatus:undefined,canonicalProject:undefined,canonicalProjectSlug:undefined,developer:undefined})});
test('malformed/API failures produce safe health and use last-known-good',async()=>{clearDldTokenCache();const dir=await mkdtemp(join(tmpdir(),'dld-')),path=join(dir,'cache.json');await writeFile(path,JSON.stringify({status:'verified',records:[{sourceId:'old'}],retrievedAt:'2026-09-12T00:00:00Z'}));const result=await fetchDldSnapshot({env,cachePath:path,retries:0,fetchImpl:async url=>String(url).includes('/token')?response({access_token:'t'}):response({unexpected:true})});assert.equal(result.status,'stale');assert.equal(result.health.status,'DEGRADED');assert.equal(result.health.last_known_good_available,true);assert.doesNotMatch(JSON.stringify(result),/secret|private-token/)});
test('missing credentials is accurately evidence-gated',async()=>{const result=await fetchDldSnapshot({env:{},cachePath:join(await mkdtemp(join(tmpdir(),'dld-')),'none.json')});assert.equal(result.status,'unavailable');assert.equal(result.health.status,'READY_FOR_CREDENTIALS');assert.equal(result.health.configured,false);assert.deepEqual(result.records,[])});
test('request timeout becomes unavailable without invented metrics',async()=>{clearDldTokenCache();const result=await fetchDldSnapshot({env,timeoutMs:5,cachePath:join(await mkdtemp(join(tmpdir(),'dld-')),'none.json'),fetchImpl:(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(Error('aborted'),{name:'AbortError'}))))});assert.equal(result.status,'unavailable');assert.equal(result.health.failure_reason,'request_timeout');assert.ok(!('transaction_count' in result))});
test('aggregation calculates values and suppresses insufficient samples',()=>{const records=[raw('1',1000,10),raw('2',2000,10),raw('3',3000,10),raw('4',4000,10),raw('5',5000,10)].map(r=>normalizeDldRecords([r]).records[0]);const result=aggregateDldTransactions(records,{generatedAt:'2026-09-13T00:00:00Z'});assert.equal(result.transaction_count,5);assert.equal(result.total_transaction_value_aed,15000);assert.equal(result.median_transaction_value_aed,3000);assert.ok(Math.abs(result.average_aed_sqft-27.871)<.01);assert.equal(result.sample_size,5);assert.ok(result.methodology);assert.equal(aggregateDldTransactions(records.slice(0,4)),null)});
test('generated source health contract contains no credentials',async()=>{const health=JSON.parse(await readFile('generated/data-health/dld.json','utf8').catch(()=>'{"status":"READY_FOR_CREDENTIALS"}'));assert.doesNotMatch(JSON.stringify(health),/API_SECRET|apiKey|secret/i)});

test('derived sqft fields and governed mappings are deterministic',async()=>{const {normalizeDldRecord}=await import('../data-sources/dld/normalize.js');const {mapDldArea,mapDldProject}=await import('../data-sources/dld/mapping.js');const record=normalizeDldRecord({...raw('mapped'),area_name_en:'AL BARSHAA SOUTH THIRD'},{mapArea:mapDldArea,mapProject:mapDldProject});assert.equal(record.propertySizeSqft,107.639);assert.ok(Math.abs(record.aedPerSqft-9.2903)<.001);assert.equal(record.canonicalAreaSlug,'al-barsha-south');assert.equal(record.areaMappingStatus,'ALIAS_VERIFIED');assert.equal(record.projectMappingStatus,'UNMAPPED')});
test('streaming CSV handles BOM and rejects malformed rows',async()=>{const {streamCsvRows,validateDldHeaders}=await import('../data-sources/dld/csv.js');const dir=await mkdtemp(join(tmpdir(),'dld-csv-')),file=join(dir,'input.csv');await writeFile(file,'\uFEFFtransaction_id,transaction_date,actual_worth\n1,2026-01-01,100\n2,bad,200,extra\n');const rows=[];for await(const row of streamCsvRows(file))rows.push(row);assert.equal(rows[0].record.transaction_id,'1');assert.equal(rows[1].error,'column_count_mismatch');assert.throws(()=>validateDldHeaders(['transaction_id']),/Missing required/)});
