import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createSession } from '../api/_lib/auth.js';
import handler, { ingestionErrorCategory } from '../api/_lib/project-ingestion-route.js';
import { projectKey, validateImport } from '../api/_lib/project-ingestion.js';
import { matchProperties, unitTypeMatchRecord } from '../api/_lib/property-matching.js';
import { discoverOpportunities, discoverPreLaunchOpportunities } from '../api/_lib/acquisition.js';
import { parseUnitTypesTextarea } from '../public/project-ingestion-form.js';

const project={developer:'TEST Developer',name:'TEST Marina Residence',emirate:'Dubai',area:'Dubai Marina',construction_status:'Off-plan',payment_plan_summary:'60/40',attributes:{tenure:'Freehold'}};
const inventory={unit:'TEST-101',property_type:'Apartment',bedrooms:'2',minimum_price:1100000,maximum_price:1200000,minimum_size:900,maximum_size:950,payment_plan_summary:'60/40'};
const payload=(extra={})=>({project,inventory:[inventory],sources:[],is_test:true,...extra});

test('structured project and inventory facts normalize without fabrication',async()=>{const result=await validateImport(payload());assert.equal(result.success,true);assert.deepEqual(result.issues,[]);assert.equal(result.data.inventory[0].price_per_sqft,undefined);assert.equal(result.data.project.attributes.tenure,'Freehold');});
test('project identity is deterministic across spacing and case',()=>assert.equal(projectKey(project),projectKey({...project,developer:' test  developer ',name:'test marina residence'})));
test('duplicate units in one import are blocked from approval',async()=>{const result=await validateImport(payload({inventory:[inventory,{...inventory}]}));assert.match(result.issues[0].message,/Duplicate unit/);});
test('malformed rows and unsafe files are rejected or flagged',async()=>{const rows=await validateImport(payload({inventory:[{...inventory,unit:'',minimum_price:2,maximum_price:1}]}));assert.ok(rows.issues.length>=2);const pdf=await validateImport(payload({sources:[{filename:'fake.pdf',media_type:'application/pdf',base64:Buffer.from('not pdf').toString('base64')}]}));assert.equal(pdf.success,false);assert.match(pdf.issues[0].message,/does not match the declared type/);});
test('CSV inventory is mapped into the same production inventory shape',async()=>{const csv='Unit,Property Type,Bedrooms,Price,Area,Payment Plan\nTEST-202,Villa,3,2500000,2100,50/50\n';const result=await validateImport(payload({inventory:[],sources:[{filename:'inventory.csv',media_type:'text/csv',base64:Buffer.from(csv).toString('base64')}]}));assert.equal(result.data.inventory[0].unit,'TEST-202');assert.equal(result.data.inventory[0].minimum_price,2500000);});
test('missing optional pre-launch facts remain empty without preventing review',async()=>{const result=await validateImport(payload({project:{developer:'TEST Developer',name:'Incomplete',attributes:{}},inventory:[]}));assert.equal(result.data.project.area,undefined);assert.deepEqual(result.issues,[]);});

test('brochure-only pre-launch is valid without physical units or unit numbers',async()=>{const result=await validateImport({project:{developer:'TEST Developer',name:'Early Launch',availability_mode:'PRE_LAUNCH',attributes:{}},unit_types:[],inventory:[],sources:[{filename:'brochure.pdf',media_type:'application/pdf',source_kind:'brochure',base64:Buffer.from('%PDF-1.4 test fixture').toString('base64')}],is_test:true});assert.equal(result.success,true);assert.equal(result.data.inventory.length,0);assert.deepEqual(result.issues,[]);});
test('live inventory mode requires a real physical unit',async()=>{const result=await validateImport({project:{developer:'TEST Developer',name:'Live',availability_mode:'LIVE_INVENTORY',attributes:{}},inventory:[],unit_types:[],sources:[],is_test:true});assert.match(result.issues[0].message,/require at least one physical unit/);});
test('multiple sourced unit types preserve factual ranges and starting prices',async()=>{const unit_types=[{unit_type:'1 Bedroom',bedrooms:'1',property_type:'Apartment',minimum_area:750,maximum_area:900,starting_price:1250000,price_currency:'AED',source_reference:'brochure.pdf p.12'},{unit_type:'2 Bedroom',bedrooms:'2',property_type:'Apartment',minimum_area:1100,starting_price:1800000,source_reference:'price-list.pdf'}];const result=await validateImport({...payload({inventory:[]}),unit_types});assert.equal(result.data.unit_types.length,2);assert.equal(result.data.unit_types[1].maximum_area,undefined);assert.equal(result.data.unit_types[1].approximate_psf,undefined);});
test('unit type textarea JSON is parsed exactly once into an array',async()=>{const value=JSON.stringify([{unit_type:'1 Bedroom'}]);assert.deepEqual(parseUnitTypesTextarea(value),[{unit_type:'1 Bedroom'}]);assert.throws(()=>parseUnitTypesTextarea(JSON.stringify(value)),/Unit types JSON is invalid/);assert.throws(()=>parseUnitTypesTextarea('[{"unit_type":]'),/Unit types JSON is invalid/);});
test('API validation rejects JSON strings before SQL with a field-level unit types error',async()=>{for(const unit_types of [JSON.stringify([]),JSON.stringify(JSON.stringify([]))]){const result=await validateImport(payload({unit_types}));assert.equal(result.success,false);assert.deepEqual(result.issues[0].path,['unit_types']);assert.equal(result.issues[0].message,'Unit types JSON is invalid');}});
test('invalid dates and prices produce field-level validation issues before persistence',async()=>{const result=await validateImport(payload({project:{...project,launch_date:'2026-02-30',eoi_amount:'not-a-price'}}));assert.equal(result.success,false);assert.deepEqual(result.issues.map(x=>x.path.join('.')).sort(),['project.eoi_amount','project.launch_date']);});
test('database failures are mapped to safe actionable diagnostic categories',async()=>{assert.equal(ingestionErrorCategory({code:'23503'}),'DATA_VALIDATION');assert.equal(ingestionErrorCategory({code:'42703'}),'SCHEMA_MISMATCH');assert.equal(ingestionErrorCategory(new Error('unexpected')),'PERSISTENCE_FAILURE');});
test('malformed unit-type JSON has an actionable browser error instead of a generic failure',async()=>{const script=await readFile('public/admin.js','utf8');assert.match(script,/parseUnitTypesTextarea/);assert.match(script,/Request ID:/);assert.match(script,/x\.path\?\.join\('\.'\)/);});

test('migration enforces inactive review gates, TEST separation and deterministic upsert without touching Amberhall',async()=>{const sql=await readFile('database/migrations/013_project_ingestion.sql','utf8');assert.match(sql,/CHECK \(NOT active OR review_status='verified'\)/);assert.match(sql,/UNIQUE\(project_key,is_test\)/);assert.match(sql,/property_inventory_import_identity_unique/);assert.match(sql,/review_status TEXT NOT NULL DEFAULT 'verified'/);assert.doesNotMatch(sql,/\bDELETE FROM|\bTRUNCATE|BAMH-1545|BAMH-634/i);});
test('pre-launch migration is additive, provenance-aware, and preserves production records',async()=>{const sql=await readFile('database/migrations/014_pre_launch_projects.sql','utf8');assert.match(sql,/project_unit_types/);assert.match(sql,/PRE_LAUNCH/);assert.match(sql,/source_kind/);assert.match(sql,/launch_date/);assert.match(sql,/eoi_amount/);assert.doesNotMatch(sql,/\bDELETE FROM|\bTRUNCATE|\bUPDATE\s/i);});

test('only SUPER_ADMIN can access ingestion and mutating requests require same origin',async()=>{process.env.SESSION_SECRET='s'.repeat(32);const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},end(value){this.body=JSON.parse(value);}});for(const role of ['ADMIN','AGENT']){const res=response();await handler({method:'GET',headers:{cookie:`fs_admin=${createSession({id:'test',role,display_name:'Test'})}`}},res);assert.equal(res.statusCode,403);}const res=response();await handler({method:'POST',headers:{cookie:`fs_admin=${createSession()}`},body:payload()},res);assert.equal(res.statusCode,403);});

test('approved inventory shape connects to matching and SEO while unverified inventory stays excluded',async()=>{const item={id:'test-inventory',...inventory,developer:project.developer,project:project.name,emirate:project.emirate,area:project.area,construction_status:project.construction_status,status:'active',data_quality:'verified',source:'project_ingestion:test',last_updated:new Date().toISOString(),is_test:true};const lead={id:'test-lead',status:'qualified',budget:'AED 1m - 1.5m',property_type:'Apartment',bedrooms:'2',preferred_areas:'Dubai Marina',emirate:'Dubai',purchase_timeline:'1-3 months',is_test:true};assert.equal(matchProperties(lead,[item]).matches[0].project,project.name);const production={...item,id:'production-view',is_test:false};assert.ok(discoverOpportunities([production,{...production,id:'production-view-2',unit:'TEST-102'}]).some(x=>x.project===project.name));assert.equal(discoverOpportunities([{...production,data_quality:'advisory',status:'inactive'}]).length,0);});

test('verified pre-launch unit types match without claiming an available unit',async()=>{const p={id:'p1',...project,availability_mode:'PRE_LAUNCH',review_status:'verified'};const type={id:'ut1',project_id:'p1',unit_type:'2 Bedroom',bedrooms:'2',property_type:'Apartment',starting_price:1800000,minimum_area:1000,review_status:'verified',source_reference:'price-list.pdf',updated_at:new Date().toISOString(),is_test:true};const record=unitTypeMatchRecord(p,type);const result=matchProperties({status:'qualified',budget:'AED 2m',property_type:'Apartment',bedrooms:'2',preferred_areas:'Dubai Marina',emirate:'Dubai',purchase_timeline:'3 months',is_test:true},[record]);assert.equal(result.matches[0].match_kind,'PROJECT/UNIT-TYPE MATCH');assert.equal(result.matches[0].inventory_id,null);assert.match(result.matches[0].advisor_talking_points[1],/No physical unit/);});
test('SEO permits verified pre-launch facts but emits no unit availability claim',async()=>{const projects=[{id:'p1',developer:'Developer',name:'Launch',area:'Dubai Marina',availability_mode:'PRE_LAUNCH',review_status:'verified',active:true,is_test:false}];const pages=discoverPreLaunchOpportunities(projects,[{id:'ut1',project_id:'p1',unit_type:'2 Bedroom',review_status:'verified',starting_price:1800000,price_currency:'AED',is_test:false}]);assert.equal(pages.length,2);assert.ok(pages.every(x=>/NOT/.test(x.availability_claim)));assert.equal(discoverPreLaunchOpportunities([{...projects[0],review_status:'needs_review'}],[]).length,0);});
