import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync } from 'node:crypto';
import { buildOpportunities,connectionState,fetchSearchConsoleReport,fingerprint,importSchema,validateSeoAction } from '../api/_lib/search-console.js';
const base={query:'Marina apartments',page:'https://finding-stories.com/dubai/marina',clicks:1,impressions:200,ctr:.005,position:12,date:'2026-08-20',device:'mobile',country:'ARE'};
const batch={report_start:'2026-08-20',report_end:'2026-08-20',source:'google_search_console',environment:'test',is_test:true,rows:[base]};
test('validates GSC ingestion and deterministic duplicate fingerprint',()=>{assert.equal(importSchema.safeParse(batch).success,true);assert.equal(fingerprint(base,batch),fingerprint(base,batch));assert.notEqual(fingerprint({...base,date:'2026-08-21'},batch),fingerprint(base,batch));});
test('enforces TEST isolation',()=>assert.equal(importSchema.safeParse({...batch,environment:'production'}).success,false));
test('detects low CTR, near page one, zero lead, inventory gap, and missing page',()=>{const rows=[{...base,is_test:false}];const types=new Set(buildOpportunities(rows).map(x=>x.type));for(const type of ['high_impressions_low_ctr','near_page_one','traffic_zero_leads','inventory_gap','missing_page'])assert(types.has(type));});
test('detects stale pages and query-to-lead attribution without inference',()=>{const lead={is_test:false,source:'organic',search_query:base.query,landing_page:base.page,status:'booked',qualified_at:'x',meeting_at:'x',site_visit_at:'x'};const result=buildOpportunities([{...base,is_test:false}],{pages:[{url:base.page,updated_at:'2025-01-01'}],inventory:[{is_test:false,status:'active',data_quality:'verified',area:'Marina'}],leads:[lead],now:new Date('2026-08-26')});assert(result.some(x=>x.type==='stale_page'));assert.deepEqual(result[0].metrics,{enquiries:1,qualified_leads:1,meetings:1,site_visits:1,bookings:1});});
test('test metrics never enter production opportunities',()=>assert.equal(buildOpportunities([{...base,is_test:true}]).length,0));
test('genuine dated periods identify growing queries and declining pages',()=>{const rows=[{...base,is_test:false,date:'2026-08-01',impressions:100},{...base,is_test:false,date:'2026-08-20',impressions:20},{...base,is_test:false,query:'Growing',date:'2026-08-01',impressions:20},{...base,is_test:false,query:'Growing',date:'2026-08-20',impressions:40}];const types=new Set(buildOpportunities(rows).map(x=>x.type));assert(types.has('growing_query'));assert(types.has('declining_page'));});
test('missing credentials are explicit and expose names, not secrets',()=>{const state=connectionState({});assert.equal(state.status,'NOT CONNECTED');assert(state.missing.includes('GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY'));});
test('connected import authenticates with Google and maps only genuine report rows',async()=>{const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});const calls=[];const responses=[{ok:true,json:async()=>({access_token:'token'})},{ok:true,json:async()=>({rows:[{keys:['2026-08-20','jvc apartment','https://www.finding-stories.com/dubai/jvc','mobile','are'],clicks:2,impressions:50,ctr:.04,position:7}]})}];const rows=await fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:{GOOGLE_SEARCH_CONSOLE_SITE_URL:'sc-domain:finding-stories.com',GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL:'reader@example.iam.gserviceaccount.com',GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY:privateKey.export({type:'pkcs8',format:'pem'})},fetchImpl:async(url,options)=>{calls.push({url,options});return responses.shift();}});assert.equal(calls.length,2);assert.match(calls[1].url,/sc-domain%3Afinding-stories\.com/);assert.deepEqual(rows[0],{date:'2026-08-20',query:'jvc apartment',page:'https://www.finding-stories.com/dubai/jvc',device:'mobile',country:'are',clicks:2,impressions:50,ctr:.04,position:7});});

const credentials=()=>{const {privateKey}=generateKeyPairSync('rsa',{modulusLength:2048});return {GOOGLE_SEARCH_CONSOLE_SITE_URL:'sc-domain:finding-stories.com',GOOGLE_SEARCH_CONSOLE_CLIENT_EMAIL:'reader@example.iam.gserviceaccount.com',GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY:privateKey.export({type:'pkcs8',format:'pem'})};};
test('uses the Search Console API host, exact encoded Domain property, readonly scope, OAuth audience, and RS256 JWT',async()=>{const calls=[];await fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:credentials(),fetchImpl:async(url,options)=>{calls.push({url,options});return calls.length===1?{ok:true,json:async()=>({access_token:'not-a-real-token'})}:{ok:true,json:async()=>({})};}});const assertion=new URLSearchParams(calls[0].options.body).get('assertion');const [header,claims]=assertion.split('.').slice(0,2).map(x=>JSON.parse(Buffer.from(x,'base64url')));assert.equal(header.alg,'RS256');assert.equal(claims.scope,'https://www.googleapis.com/auth/webmasters.readonly');assert.equal(claims.aud,'https://oauth2.googleapis.com/token');assert.equal(calls[0].url,'https://oauth2.googleapis.com/token');assert.equal(calls[1].url,'https://searchconsole.googleapis.com/webmasters/v3/sites/sc-domain%3Afinding-stories.com/searchAnalytics/query');});
test('accepts a genuine zero-row Search Analytics response',async()=>{let call=0;const rows=await fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:credentials(),fetchImpl:async()=>++call===1?{ok:true,json:async()=>({access_token:'not-a-real-token'})}:{ok:true,json:async()=>({})}});assert.deepEqual(rows,[]);});
test('classifies configuration, malformed key, OAuth, permission, disabled API, 401, 404, and quota failures without response bodies',async()=>{
 await assert.rejects(fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:{}}),x=>x.code==='credentials_missing'&&x.stage==='configuration');
 await assert.rejects(fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:{...credentials(),GOOGLE_SEARCH_CONSOLE_PRIVATE_KEY:'secret-invalid-value'}}),x=>x.code==='malformed_private_key');
 const run=async(status,payload,stage='report')=>{let call=0;return fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:credentials(),fetchImpl:async()=>{call++;if(stage==='oauth'||call===2)return {ok:false,status,json:async()=>payload};return {ok:true,json:async()=>({access_token:'not-a-real-token'})};}});};
 await assert.rejects(run(400,{error:{message:'sensitive credential detail'}},'oauth'),x=>x.code==='oauth_token_exchange_failed'&&!x.message.includes('sensitive'));
 await assert.rejects(run(403,{error:{status:'PERMISSION_DENIED'}}),x=>x.code==='property_permission_denied');
 await assert.rejects(run(403,{error:{status:'PERMISSION_DENIED',message:'API is disabled'}}),x=>x.code==='api_disabled');
 await assert.rejects(run(401,{error:{message:'token detail'}}),x=>x.code==='google_401');
 await assert.rejects(run(404,{error:{message:'property detail'}}),x=>x.code==='google_404');
 await assert.rejects(run(429,{error:{message:'quota detail'}}),x=>x.code==='google_quota');
});
test('rejects URL-prefix properties instead of silently converting a Domain property',async()=>{await assert.rejects(fetchSearchConsoleReport({startDate:'2026-08-01',endDate:'2026-08-20',env:{...credentials(),GOOGLE_SEARCH_CONSOLE_SITE_URL:'https://finding-stories.com/'}}),x=>x.code==='invalid_property_identifier');});

test('approval gating accepts only auditable non-publishing actions',()=>{assert.equal(validateSeoAction({recommendation_id:'abc',status:'approved',action_type:'improve_cta'}),true);assert.equal(validateSeoAction({recommendation_id:'abc',status:'published',action_type:'publish_page'}),false);});
