import {createHash} from 'node:crypto';import {createReadStream} from 'node:fs';import {appendFile,mkdir,readFile,rename,stat,writeFile} from 'node:fs/promises';import {basename,resolve} from 'node:path';
import {streamCsvRows} from '../data-sources/dld/csv.js';import {normalizeDldRecord} from '../data-sources/dld/normalize.js';import {mapDldArea,mapDldProject} from '../data-sources/dld/mapping.js';import {withDldProvenance,DLD_SOURCE} from '../data-sources/dld/provenance.js';import {aggregateDldDimensions} from '../data-sources/dld/aggregate.js';import {writeLastKnownGood} from '../data-sources/dld/cache.js';
import {generateDldMappingReview} from '../data-sources/dld/mapping-review.js';
const args=Object.fromEntries(process.argv.slice(2).map(arg=>arg.replace(/^--/,'').split(/=(.*)/s).slice(0,2)));if(!args.file)throw new Error('Usage: npm run dld:import -- --file=/path/to/Transactions.csv [--source-url=https://official.example/file.csv] [--start=YYYY-MM-DD] [--end=YYYY-MM-DD]');
const file=resolve(args.file),info=await stat(file);if(!info.isFile())throw new Error('DLD import path must be a file');const retrievedAt=new Date().toISOString(),hash=createHash('sha256');for await(const chunk of createReadStream(file))hash.update(chunk);const checksum=hash.digest('hex');
await mkdir('generated/intelligence/dld',{recursive:true});const spool=`generated/intelligence/dld/.normalized-${process.pid}.partial`;await writeFile(spool,'');const seen=new Set(),records=[],areas=new Set(),projects=new Set();let read=0,rejected=0,duplicates=0;
for await(const row of streamCsvRows(file,{startDate:args.start,endDate:args.end})){read++;if(row.error){rejected++;continue}try{const normalized=normalizeDldRecord(row.record,{mapArea:mapDldArea,mapProject:mapDldProject});if(seen.has(normalized.sourceId)){duplicates++;continue}seen.add(normalized.sourceId);const record=withDldProvenance(normalized,{retrievedAt});records.push(record);await appendFile(spool,`${JSON.stringify(record)}\n`);if(record.areaMappingStatus==='UNMAPPED'&&record.sourceAreaName)areas.add(record.sourceAreaName);if(record.projectMappingStatus==='UNMAPPED'&&record.project)projects.add(record.project);if(read%25000===0)console.log(`Progress: ${read.toLocaleString('en-US')} rows read; ${records.length.toLocaleString('en-US')} accepted`)}catch{rejected++}}
const generatedAt=new Date().toISOString(),metrics=aggregateDldDimensions(records,{generatedAt,minimumSampleSize:Number(args['minimum-sample']??5)}),period=records.map(r=>r.transactionDate).sort();const artifact={status:'verified',source:{name:'Dubai Land Department',url:args['source-url']??DLD_SOURCE.url},updated:retrievedAt,period_start:period[0]??null,period_end:period.at(-1)??null,metrics};
await writeFile('generated/intelligence/dld/market-metrics.json',`${JSON.stringify(artifact,null,2)}\n`);await rename(spool,'generated/intelligence/dld/normalized-transactions.jsonl');await writeLastKnownGood('generated/intelligence/latest-market-snapshot.json',{status:'verified',stale:false,records,retrievedAt,sourceUpdatedAt:null});
const manifestPath='data-import/dld/manifest.json',manifest=JSON.parse(await readFile(manifestPath,'utf8'));manifest.imports.push({file_name:basename(file),source_url:args['source-url']??DLD_SOURCE.url,retrieved_at:retrievedAt,file_checksum_sha256:checksum,file_size_bytes:info.size,row_count:records.length,period_start:artifact.period_start,period_end:artifact.period_end,schema_version:'1.0'});await writeFile(manifestPath,`${JSON.stringify(manifest,null,2)}\n`);
const mappedAreaRecords=records.filter(record=>record.areaMappingStatus!=='UNMAPPED'),mappedProjectRecords=records.filter(record=>record.projectMappingStatus!=='UNMAPPED');
const health={mode:'OFFICIAL_CSV',source_available:true,retrieval_status:'SUCCESS',status:'HEALTHY',last_attempt:retrievedAt,last_success:retrievedAt,source_freshness:artifact.period_end,generation_timestamp:generatedAt,records_retrieved:read,valid_records:records.length,rejected_records:rejected,duplicate_records:duplicates,mapped_area_records:mappedAreaRecords.length,unmapped_area_records:records.length-mappedAreaRecords.length,confidently_mapped_project_records:mappedProjectRecords.length,unresolved_project_records:records.length-mappedProjectRecords.length,last_known_good_status:'WRITTEN',last_known_good_available:true,checksum_sha256:checksum};await mkdir('generated/data-health',{recursive:true});await writeFile('generated/data-health/dld.json',`${JSON.stringify(health,null,2)}\n`);
await generateDldMappingReview(records);
console.log(`Rows read: ${read}\nAccepted: ${records.length}\nRejected: ${rejected}\nDuplicates: ${duplicates}\nAreas matched: ${new Set(records.filter(r=>r.areaMappingStatus!=='UNMAPPED').map(r=>r.canonicalAreaSlug)).size}\nAreas unmapped: ${areas.size}\nProjects matched: ${new Set(records.filter(r=>r.projectMappingStatus!=='UNMAPPED').map(r=>r.canonicalProjectSlug)).size}\nProjects unmapped: ${projects.size}\nPeriod covered: ${artifact.period_start??'unavailable'} to ${artifact.period_end??'unavailable'}\nSource: Dubai Land Department\nStatus: HEALTHY`);
